<?php

namespace AppBundle\Repository;

/**
 * AttendanceInRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendanceInRepository extends \Doctrine\ORM\EntityRepository
{
}
