<?php

namespace AppBundle\Repository;

/**
 * CheckInRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckInRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTime($date, $userId)
    {
        $query = $this->createQueryBuilder('check_in')
            ->leftJoin('check_in.user', 'user') // use contextual help to see the associations
            ->andWhere('user.id = :id')
            ->setParameter('id', $userId)
            ->addOrderBy('a.createdAt', 'DESC')
            ->addSelect('author') // avoid lazy loading in views
            ->getQuery()
        ;

        return $query;
    }

    public function getCheckInByUserDate(\DateTime $date1, \DateTime $date2, $userId)
    {
        $query = $this->createQueryBuilder('check_in')
            ->leftJoin('check_in.user', 'user')
            ->andWhere('user.id = :id')
            ->andWhere('check_in.createdAt BETWEEN :date1 AND :date2')
            ->setParameter('date1', $date1)
            ->setParameter('date2', $date2)
            ->setParameter('id', $userId)
            ->orderBy('check_in.createdAt', 'DESC')
            ->getQuery()
        ;

        return $query->execute();
    }
}
