<?php

namespace AppBundle\Repository;

/**
 * CheckOutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckOutRepository extends \Doctrine\ORM\EntityRepository
{
}
