app_admin_user:
    resource: "@AppBundle/Controller/Admin/UserController.php"
    type:     annotation
    prefix:   /admin/users

app_admin_attendance:
    resource: "@AppBundle/Controller/Admin/AttendanceController.php"
    type:     annotation
    prefix:   /admin/attendance

app_attendance:
    resource: "@AppBundle/Controller/AttendanceController.php"
    type:     annotation

app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /profile

security:
    resource: "@AppBundle/Controller/SecurityController.php"
    type:     annotation

app_checkins:
    resource: "@AppBundle/Controller/CheckInController.php"
    type:     annotation
    prefix:   /checkins

app_checkouts:
    resource: "@AppBundle/Controller/CheckOutController.php"
    type:     annotation
    prefix:   /checkouts

app_absences:
    resource: "@AppBundle/Controller/AbsenceController.php"
    type:     annotation
    prefix:   /absences