app_admin:
    resource: "@AppBundle/Controller/Admin/UserController.php"
    type:     annotation
    prefix:   /admin/users

app_attendance:
    resource: "@AppBundle/Controller/AttendanceController.php"
    type:     annotation

app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /profile

security:
    resource: "@AppBundle/Controller/SecurityController.php"
    type:     annotation