app_admin:
    resource: "@AppBundle/Controller/Admin/UserController.php"
    type:     annotation
    prefix:   /admin/users

app:
    resource: "@AppBundle/Controller/AttendanceController.php"
    type:     annotation

security:
    resource: "@AppBundle/Controller/SecurityController.php"
    type:     annotation