parameters:

services:
    app.doctrine.userListener:
        class: AppBundle\Doctrine\UserListener
        arguments: ["@security.encoder_factory"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    app.service.timeService:
        class: AppBundle\Service\TimeService